//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.2045
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Error", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Load chart error.  的本地化字符串。
        /// </summary>
        internal static string ERR_CHART_LOAD {
            get {
                return ResourceManager.GetString("ERR_CHART_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change email error.  的本地化字符串。
        /// </summary>
        internal static string ERR_EMAIL_CHANGE {
            get {
                return ResourceManager.GetString("ERR_EMAIL_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input contact name 的本地化字符串。
        /// </summary>
        internal static string ERR_INPUT_CONTACT {
            get {
                return ResourceManager.GetString("ERR_INPUT_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input email address  的本地化字符串。
        /// </summary>
        internal static string ERR_INPUT_EMAIL {
            get {
                return ResourceManager.GetString("ERR_INPUT_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input lease number  的本地化字符串。
        /// </summary>
        internal static string ERR_INPUT_LEASE {
            get {
                return ResourceManager.GetString("ERR_INPUT_LEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input phone number 的本地化字符串。
        /// </summary>
        internal static string ERR_INPUT_PHONE {
            get {
                return ResourceManager.GetString("ERR_INPUT_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input password  的本地化字符串。
        /// </summary>
        internal static string ERR_INPUT_PSW {
            get {
                return ResourceManager.GetString("ERR_INPUT_PSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input your verification code and password 的本地化字符串。
        /// </summary>
        internal static string ERR_INPUT_PSW_VCODE {
            get {
                return ResourceManager.GetString("ERR_INPUT_PSW_VCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select and answer security questions 的本地化字符串。
        /// </summary>
        internal static string ERR_INPUT_QUESTION {
            get {
                return ResourceManager.GetString("ERR_INPUT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input verification code  的本地化字符串。
        /// </summary>
        internal static string ERR_INPUT_VCODE {
            get {
                return ResourceManager.GetString("ERR_INPUT_VCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change language error.  的本地化字符串。
        /// </summary>
        internal static string ERR_LANG_CHANGE {
            get {
                return ResourceManager.GetString("ERR_LANG_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change lease error.  的本地化字符串。
        /// </summary>
        internal static string ERR_LEASE_CHANGE {
            get {
                return ResourceManager.GetString("ERR_LEASE_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete error.  的本地化字符串。
        /// </summary>
        internal static string ERR_LINKE_LEASE_DEL {
            get {
                return ResourceManager.GetString("ERR_LINKE_LEASE_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link lease error.  的本地化字符串。
        /// </summary>
        internal static string ERR_LINK_LEASE {
            get {
                return ResourceManager.GetString("ERR_LINK_LEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login failed  的本地化字符串。
        /// </summary>
        internal static string ERR_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("ERR_LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network error  的本地化字符串。
        /// </summary>
        internal static string ERR_NETWORK_ERR {
            get {
                return ResourceManager.GetString("ERR_NETWORK_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load notice error.  的本地化字符串。
        /// </summary>
        internal static string ERR_NOTICE_GET {
            get {
                return ResourceManager.GetString("ERR_NOTICE_GET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download pdf error  的本地化字符串。
        /// </summary>
        internal static string ERR_PDF_DOWNLOAD {
            get {
                return ResourceManager.GetString("ERR_PDF_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load pdf error  的本地化字符串。
        /// </summary>
        internal static string ERR_PDF_LOAD {
            get {
                return ResourceManager.GetString("ERR_PDF_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change password failed.  的本地化字符串。
        /// </summary>
        internal static string ERR_PSW_CHANGE {
            get {
                return ResourceManager.GetString("ERR_PSW_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input your current password 的本地化字符串。
        /// </summary>
        internal static string ERR_PSW_CURRENT {
            get {
                return ResourceManager.GetString("ERR_PSW_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password length error (Between 6 to 20)  的本地化字符串。
        /// </summary>
        internal static string ERR_PSW_LENGTH {
            get {
                return ResourceManager.GetString("ERR_PSW_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input new password  的本地化字符串。
        /// </summary>
        internal static string ERR_PSW_NEW {
            get {
                return ResourceManager.GetString("ERR_PSW_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input same password  的本地化字符串。
        /// </summary>
        internal static string ERR_PSW_SAME {
            get {
                return ResourceManager.GetString("ERR_PSW_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification failed.  的本地化字符串。
        /// </summary>
        internal static string ERR_QUESTION_VERIFICATION {
            get {
                return ResourceManager.GetString("ERR_QUESTION_VERIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register failed  的本地化字符串。
        /// </summary>
        internal static string ERR_REG_FAILED {
            get {
                return ResourceManager.GetString("ERR_REG_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get verification code error.  的本地化字符串。
        /// </summary>
        internal static string ERR_VCODE_GET {
            get {
                return ResourceManager.GetString("ERR_VCODE_GET", resourceCulture);
            }
        }
    }
}
