//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Approve success 的本地化字符串。
        /// </summary>
        internal static string Res_Alert_Approve_0 {
            get {
                return ResourceManager.GetString("Res_Alert_Approve_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select to approve 的本地化字符串。
        /// </summary>
        internal static string Res_Alert_Approve_1 {
            get {
                return ResourceManager.GetString("Res_Alert_Approve_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve error 的本地化字符串。
        /// </summary>
        internal static string Res_Alert_Approve_2 {
            get {
                return ResourceManager.GetString("Res_Alert_Approve_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve 的本地化字符串。
        /// </summary>
        internal static string Res_Approve {
            get {
                return ResourceManager.GetString("Res_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approver 的本地化字符串。
        /// </summary>
        internal static string Res_Approver {
            get {
                return ResourceManager.GetString("Res_Approver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority 的本地化字符串。
        /// </summary>
        internal static string Res_Authority {
            get {
                return ResourceManager.GetString("Res_Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Id 的本地化字符串。
        /// </summary>
        internal static string Res_Authority_Id {
            get {
                return ResourceManager.GetString("Res_Authority_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authority Type 的本地化字符串。
        /// </summary>
        internal static string Res_Authority_Type {
            get {
                return ResourceManager.GetString("Res_Authority_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change email 的本地化字符串。
        /// </summary>
        internal static string Res_ChangeEmail {
            get {
                return ResourceManager.GetString("Res_ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        internal static string Res_ChangeEmail_CheckUser {
            get {
                return ResourceManager.GetString("Res_ChangeEmail_CheckUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Name 的本地化字符串。
        /// </summary>
        internal static string Res_ChangeEmail_ContactName {
            get {
                return ResourceManager.GetString("Res_ChangeEmail_ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Email 的本地化字符串。
        /// </summary>
        internal static string Res_ChangeEmail_NewEmail {
            get {
                return ResourceManager.GetString("Res_ChangeEmail_NewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Res_ChangeEmail_Password {
            get {
                return ResourceManager.GetString("Res_ChangeEmail_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone Number 的本地化字符串。
        /// </summary>
        internal static string Res_ChangeEmail_PhoneNumber {
            get {
                return ResourceManager.GetString("Res_ChangeEmail_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Success 的本地化字符串。
        /// </summary>
        internal static string Res_ChangeEmail_Success {
            get {
                return ResourceManager.GetString("Res_ChangeEmail_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update Email 的本地化字符串。
        /// </summary>
        internal static string Res_ChangeEmail_UpdateEmail {
            get {
                return ResourceManager.GetString("Res_ChangeEmail_UpdateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        internal static string Res_ChangePsw_Button {
            get {
                return ResourceManager.GetString("Res_ChangePsw_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your password has been changed 的本地化字符串。
        /// </summary>
        internal static string Res_ChangePsw_Changed {
            get {
                return ResourceManager.GetString("Res_ChangePsw_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Password 的本地化字符串。
        /// </summary>
        internal static string Res_ChangePsw_CurrentPsw {
            get {
                return ResourceManager.GetString("Res_ChangePsw_CurrentPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input correct password 的本地化字符串。
        /// </summary>
        internal static string Res_ChangePsw_Error {
            get {
                return ResourceManager.GetString("Res_ChangePsw_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        internal static string Res_ChangePsw_NewPsw1 {
            get {
                return ResourceManager.GetString("Res_ChangePsw_NewPsw1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reconfirm Password 的本地化字符串。
        /// </summary>
        internal static string Res_ChangePsw_NewPsw2 {
            get {
                return ResourceManager.GetString("Res_ChangePsw_NewPsw2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password is successfully changed 的本地化字符串。
        /// </summary>
        internal static string Res_ChangePsw_Success {
            get {
                return ResourceManager.GetString("Res_ChangePsw_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Number 的本地化字符串。
        /// </summary>
        internal static string Res_ChangePsw_UserName {
            get {
                return ResourceManager.GetString("Res_ChangePsw_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Billing 的本地化字符串。
        /// </summary>
        internal static string Res_ContactUs_Billing {
            get {
                return ResourceManager.GetString("Res_ContactUs_Billing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estate Management 的本地化字符串。
        /// </summary>
        internal static string Res_ContactUs_EstateManagement {
            get {
                return ResourceManager.GetString("Res_ContactUs_EstateManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LEASING 的本地化字符串。
        /// </summary>
        internal static string Res_ContactUs_Leasing {
            get {
                return ResourceManager.GetString("Res_ContactUs_Leasing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Name 的本地化字符串。
        /// </summary>
        internal static string Res_Contact_Name {
            get {
                return ResourceManager.GetString("Res_Contact_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Number 的本地化字符串。
        /// </summary>
        internal static string Res_Contact_Number {
            get {
                return ResourceManager.GetString("Res_Contact_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Creation 的本地化字符串。
        /// </summary>
        internal static string Res_Customer_Creation {
            get {
                return ResourceManager.GetString("Res_Customer_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name 的本地化字符串。
        /// </summary>
        internal static string Res_Customer_Name {
            get {
                return ResourceManager.GetString("Res_Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string Res_Department {
            get {
                return ResourceManager.GetString("Res_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        internal static string Res_Detail {
            get {
                return ResourceManager.GetString("Res_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. DESCRIPTION OF SERVICE 
        ///Hutchison Estate Agents Limited  (&quot;HEAL&quot;) operates a website located on the internet at [www.heal.com.hk] (&quot;Site&quot;) which provides users of the Site (&quot;User&quot;) with access to a selection of estate value-added services (&quot;Service&quot;) subject to the terms and conditions of service set out herein (&quot;Terms and Conditions&quot;). Through the use of the Service, Users will be able to: 
        ///(a) view notices, news and information relating to their estate; 
        ///(b) make reservations, check availability and [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Res_Disclaimer {
            get {
                return ResourceManager.GetString("Res_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Res_Edit {
            get {
                return ResourceManager.GetString("Res_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Customer User 的本地化字符串。
        /// </summary>
        internal static string Res_Edit_Cust_User {
            get {
                return ResourceManager.GetString("Res_Edit_Cust_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Res_Email {
            get {
                return ResourceManager.GetString("Res_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Em Phone Number 的本地化字符串。
        /// </summary>
        internal static string Res_Em_Phone_Number {
            get {
                return ResourceManager.GetString("Res_Em_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Date 的本地化字符串。
        /// </summary>
        internal static string Res_End_Date {
            get {
                return ResourceManager.GetString("Res_End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve Status 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_ApproveStatus {
            get {
                return ResourceManager.GetString("Res_Feedback_ApproveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Date {
            get {
                return ResourceManager.GetString("Res_Feedback_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Detail {
            get {
                return ResourceManager.GetString("Res_Feedback_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Id {
            get {
                return ResourceManager.GetString("Res_Feedback_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_New {
            get {
                return ResourceManager.GetString("Res_Feedback_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reply 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Reply {
            get {
                return ResourceManager.GetString("Res_Feedback_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date:  的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Search_From {
            get {
                return ResourceManager.GetString("Res_Feedback_Search_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status:  的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Search_Status {
            get {
                return ResourceManager.GetString("Res_Feedback_Search_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To:  的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Search_To {
            get {
                return ResourceManager.GetString("Res_Feedback_Search_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type:  的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Search_Type {
            get {
                return ResourceManager.GetString("Res_Feedback_Search_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Status {
            get {
                return ResourceManager.GetString("Res_Feedback_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Status_All {
            get {
                return ResourceManager.GetString("Res_Feedback_Status_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Status_Closed {
            get {
                return ResourceManager.GetString("Res_Feedback_Status_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Reply 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Status_NotReply {
            get {
                return ResourceManager.GetString("Res_Feedback_Status_NotReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pending to close 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Status_Pending2Close {
            get {
                return ResourceManager.GetString("Res_Feedback_Status_Pending2Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replied 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Status_Replied {
            get {
                return ResourceManager.GetString("Res_Feedback_Status_Replied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Submit {
            get {
                return ResourceManager.GetString("Res_Feedback_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Title {
            get {
                return ResourceManager.GetString("Res_Feedback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Type {
            get {
                return ResourceManager.GetString("Res_Feedback_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Type_All {
            get {
                return ResourceManager.GetString("Res_Feedback_Type_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleaning 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Type_Cleaning {
            get {
                return ResourceManager.GetString("Res_Feedback_Type_Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gardening 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Type_Gardening {
            get {
                return ResourceManager.GetString("Res_Feedback_Type_Gardening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Type_Others {
            get {
                return ResourceManager.GetString("Res_Feedback_Type_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Type_Security {
            get {
                return ResourceManager.GetString("Res_Feedback_Type_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Staff 的本地化字符串。
        /// </summary>
        internal static string Res_Feedback_Type_Staff {
            get {
                return ResourceManager.GetString("Res_Feedback_Type_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_ChangePsw {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_ChangePsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_ConfirmPsw {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_ConfirmPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Verification Code 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_GetCode {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_GetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Number 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_LeaseNumber {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_LeaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Password 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_Mail_0 {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_Mail_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dear Tenant, 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_Mail_1 {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_Mail_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please find below the verification code for password reset in our website. (website: www.heal.com.hk) 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_Mail_2 {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_Mail_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verification code: 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_Mail_3 {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_Mail_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yours faithfully, 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_Mail_4 {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_Mail_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hutchison Estate Agents Limited 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_Mail_5 {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_Mail_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_NewPsw {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_NewPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your verification code has been sent to your email address 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_Send_Success {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_Send_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Verification Code 的本地化字符串。
        /// </summary>
        internal static string Res_ForgetPassword_YourCode {
            get {
                return ResourceManager.GetString("Res_ForgetPassword_YourCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input your  Lease Number: 的本地化字符串。
        /// </summary>
        internal static string Res_Forgetpsw_InputUserid {
            get {
                return ResourceManager.GetString("Res_Forgetpsw_InputUserid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Agree 的本地化字符串。
        /// </summary>
        internal static string Res_Global_Agree {
            get {
                return ResourceManager.GetString("Res_Global_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Res_Global_Cancel {
            get {
                return ResourceManager.GetString("Res_Global_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Res_Global_OK {
            get {
                return ResourceManager.GetString("Res_Global_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Name 的本地化字符串。
        /// </summary>
        internal static string Res_Group_Name {
            get {
                return ResourceManager.GetString("Res_Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Last Successful Login: 的本地化字符串。
        /// </summary>
        internal static string Res_Homepage_LastLogin {
            get {
                return ResourceManager.GetString("Res_Homepage_LastLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 notification(s). 的本地化字符串。
        /// </summary>
        internal static string Res_Homepage_NewMessage {
            get {
                return ResourceManager.GetString("Res_Homepage_NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your Quick Summary 的本地化字符串。
        /// </summary>
        internal static string Res_Homepage_Summary {
            get {
                return ResourceManager.GetString("Res_Homepage_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Statement Balance:  的本地化字符串。
        /// </summary>
        internal static string Res_Homepage_TotalOutstanding {
            get {
                return ResourceManager.GetString("Res_Homepage_TotalOutstanding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome 的本地化字符串。
        /// </summary>
        internal static string Res_Homepage_Welcome {
            get {
                return ResourceManager.GetString("Res_Homepage_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have 的本地化字符串。
        /// </summary>
        internal static string Res_Homepage_YouHave {
            get {
                return ResourceManager.GetString("Res_Homepage_YouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string Res_Hompage_Menu_Info {
            get {
                return ResourceManager.GetString("Res_Hompage_Menu_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string Res_Image {
            get {
                return ResourceManager.GetString("Res_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease List 的本地化字符串。
        /// </summary>
        internal static string Res_Lease_List {
            get {
                return ResourceManager.GetString("Res_Lease_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Number  的本地化字符串。
        /// </summary>
        internal static string Res_Lease_Number {
            get {
                return ResourceManager.GetString("Res_Lease_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link New Lease 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_Button {
            get {
                return ResourceManager.GetString("Res_LinkLease_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_Button_Delete {
            get {
                return ResourceManager.GetString("Res_LinkLease_Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement Balance 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_CurrentBalance {
            get {
                return ResourceManager.GetString("Res_LinkLease_CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_Edit {
            get {
                return ResourceManager.GetString("Res_LinkLease_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expiry Date 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_ExpiryDate {
            get {
                return ResourceManager.GetString("Res_LinkLease_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Number 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_LeaseNumber {
            get {
                return ResourceManager.GetString("Res_LinkLease_LeaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linked Lease Number 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_LinkedLease {
            get {
                return ResourceManager.GetString("Res_LinkLease_LinkedLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link New Lease 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_LinkNewLease {
            get {
                return ResourceManager.GetString("Res_LinkLease_LinkNewLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Linked Lease 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_Modal_DeleteLease {
            get {
                return ResourceManager.GetString("Res_LinkLease_Modal_DeleteLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_Password {
            get {
                return ResourceManager.GetString("Res_LinkLease_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Premises 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_Premises {
            get {
                return ResourceManager.GetString("Res_LinkLease_Premises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement Number 的本地化字符串。
        /// </summary>
        internal static string Res_LinkLease_StatementNumber {
            get {
                return ResourceManager.GetString("Res_LinkLease_StatementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Res_LoginSystem_Password {
            get {
                return ResourceManager.GetString("Res_LoginSystem_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string Res_LoginSystem_Username {
            get {
                return ResourceManager.GetString("Res_LoginSystem_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Button_Login {
            get {
                return ResourceManager.GetString("Res_Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terms &amp; Conditions 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Button_Term {
            get {
                return ResourceManager.GetString("Res_Login_Button_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input lease number 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Err_1 {
            get {
                return ResourceManager.GetString("Res_Login_Err_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input password 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Err_2 {
            get {
                return ResourceManager.GetString("Res_Login_Err_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        internal static string Res_Login_FirstTimeConfirmPsw {
            get {
                return ResourceManager.GetString("Res_Login_FirstTimeConfirmPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please change your password for your first time login 的本地化字符串。
        /// </summary>
        internal static string Res_Login_FirstTimeLogin {
            get {
                return ResourceManager.GetString("Res_Login_FirstTimeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        internal static string Res_Login_FirstTimeNewPsw {
            get {
                return ResourceManager.GetString("Res_Login_FirstTimeNewPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forget password? 的本地化字符串。
        /// </summary>
        internal static string Res_Login_ForgetPassword {
            get {
                return ResourceManager.GetString("Res_Login_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Label_Password {
            get {
                return ResourceManager.GetString("Res_Login_Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Number 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Label_UserName {
            get {
                return ResourceManager.GetString("Res_Login_Label_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Name 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Name {
            get {
                return ResourceManager.GetString("Res_Login_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Register {
            get {
                return ResourceManager.GetString("Res_Login_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All information in this web site is meant for your reference only, and is not intended, nor should be construed, as investment advice. CK Asset Holdings Limited does not warrant or represent that the information provided here is complete and accurate, nor that the information is up to date. No liability will be accepted for any loss or damage howsoever arising from or in reliance upon the contents of this web site. 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Terms_Content {
            get {
                return ResourceManager.GetString("Res_Login_Terms_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login to your account 的本地化字符串。
        /// </summary>
        internal static string Res_Login_Title {
            get {
                return ResourceManager.GetString("Res_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail Recipients Setting 的本地化字符串。
        /// </summary>
        internal static string Res_Mail_Setup {
            get {
                return ResourceManager.GetString("Res_Mail_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eForm Date Define 的本地化字符串。
        /// </summary>
        internal static string Res_MenuItem_eForm_Date_Define {
            get {
                return ResourceManager.GetString("Res_MenuItem_eForm_Date_Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eForm Time Define 的本地化字符串。
        /// </summary>
        internal static string Res_MenuItem_eForm_Time_Define {
            get {
                return ResourceManager.GetString("Res_MenuItem_eForm_Time_Define", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ACCOUNT INFO 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_AccountInfo {
            get {
                return ResourceManager.GetString("Res_Menu_AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Setting 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_ChangePsw {
            get {
                return ResourceManager.GetString("Res_Menu_ChangePsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Us 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_ContactUs {
            get {
                return ResourceManager.GetString("Res_Menu_ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Creation 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_CustomerCreation {
            get {
                return ResourceManager.GetString("Res_Menu_CustomerCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eApplication 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Eforms {
            get {
                return ResourceManager.GetString("Res_Menu_Eforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eForm Define 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Eforms_Def {
            get {
                return ResourceManager.GetString("Res_Menu_Eforms_Def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eFlow Define 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Eforms_FlowDef {
            get {
                return ResourceManager.GetString("Res_Menu_Eforms_FlowDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eOperation 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Eforms_Opers {
            get {
                return ResourceManager.GetString("Res_Menu_Eforms_Opers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Setting 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_EmailSetting {
            get {
                return ResourceManager.GetString("Res_Menu_EmailSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FEEDBACK 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Feedback {
            get {
                return ResourceManager.GetString("Res_Menu_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_FeedbackMaintenance {
            get {
                return ResourceManager.GetString("Res_Menu_FeedbackMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedbacks 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Feedbacks {
            get {
                return ResourceManager.GetString("Res_Menu_Feedbacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forget Password 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_ForgetPassword {
            get {
                return ResourceManager.GetString("Res_Menu_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Homepage {
            get {
                return ResourceManager.GetString("Res_Menu_Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link Lease 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_LinkLease {
            get {
                return ResourceManager.GetString("Res_Menu_LinkLease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Logout {
            get {
                return ResourceManager.GetString("Res_Menu_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice Approve 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_NoticeApprove {
            get {
                return ResourceManager.GetString("Res_Menu_NoticeApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_NoticeMaintenance {
            get {
                return ResourceManager.GetString("Res_Menu_NoticeMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Onlinepay 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Onlinepay {
            get {
                return ResourceManager.GetString("Res_Menu_Onlinepay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My Profile 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Profile {
            get {
                return ResourceManager.GetString("Res_Menu_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PROPERTY INFO 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_PropertyInfo {
            get {
                return ResourceManager.GetString("Res_Menu_PropertyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_PropertyMgmt {
            get {
                return ResourceManager.GetString("Res_Menu_PropertyMgmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Register {
            get {
                return ResourceManager.GetString("Res_Menu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reminder Setting 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Reminder_Setting {
            get {
                return ResourceManager.GetString("Res_Menu_Reminder_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Statement {
            get {
                return ResourceManager.GetString("Res_Menu_Statement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement Date Setting 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_StatementDateSetting {
            get {
                return ResourceManager.GetString("Res_Menu_StatementDateSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Information 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_SystemInfo {
            get {
                return ResourceManager.GetString("Res_Menu_SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_SystemMaintenance {
            get {
                return ResourceManager.GetString("Res_Menu_SystemMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Group Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_UserGroupMaintenance {
            get {
                return ResourceManager.GetString("Res_Menu_UserGroupMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_UserMaintenance {
            get {
                return ResourceManager.GetString("Res_Menu_UserMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome! 的本地化字符串。
        /// </summary>
        internal static string Res_Menu_Welcome {
            get {
                return ResourceManager.GetString("Res_Menu_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Creation 的本地化字符串。
        /// </summary>
        internal static string Res_New_Creation {
            get {
                return ResourceManager.GetString("Res_New_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Group 的本地化字符串。
        /// </summary>
        internal static string Res_New_Group {
            get {
                return ResourceManager.GetString("Res_New_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New User 的本地化字符串。
        /// </summary>
        internal static string Res_New_User {
            get {
                return ResourceManager.GetString("Res_New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice Approve 的本地化字符串。
        /// </summary>
        internal static string Res_NoticeApprove {
            get {
                return ResourceManager.GetString("Res_NoticeApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_NoticeMaintenance {
            get {
                return ResourceManager.GetString("Res_NoticeMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve By 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_ApproveBy {
            get {
                return ResourceManager.GetString("Res_Notice_ApproveBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attachement 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Attachment {
            get {
                return ResourceManager.GetString("Res_Notice_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Notice 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Btn_Edit {
            get {
                return ResourceManager.GetString("Res_Notice_Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Notice 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Btn_New {
            get {
                return ResourceManager.GetString("Res_Notice_Btn_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Upload File 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_ChooseUploadFile {
            get {
                return ResourceManager.GetString("Res_Notice_ChooseUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Upload Image 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_ChooseUploadImage {
            get {
                return ResourceManager.GetString("Res_Notice_ChooseUploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Content {
            get {
                return ResourceManager.GetString("Res_Notice_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create By 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_CreateBy {
            get {
                return ResourceManager.GetString("Res_Notice_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Approve 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Grid_Approve {
            get {
                return ResourceManager.GetString("Res_Notice_Grid_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Grid_Edit {
            get {
                return ResourceManager.GetString("Res_Notice_Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Date 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Grid_End {
            get {
                return ResourceManager.GetString("Res_Notice_Grid_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Grid_Image {
            get {
                return ResourceManager.GetString("Res_Notice_Grid_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Grid_Property {
            get {
                return ResourceManager.GetString("Res_Notice_Grid_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Date 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Grid_Start {
            get {
                return ResourceManager.GetString("Res_Notice_Grid_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Grid_Subject {
            get {
                return ResourceManager.GetString("Res_Notice_Grid_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_Grid_Type {
            get {
                return ResourceManager.GetString("Res_Notice_Grid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image resolution ratio is 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_ImageResolutionIs {
            get {
                return ResourceManager.GetString("Res_Notice_ImageResolutionIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Edit Notice 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_SaveEdit {
            get {
                return ResourceManager.GetString("Res_Notice_SaveEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save New Notice 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_SaveNew {
            get {
                return ResourceManager.GetString("Res_Notice_SaveNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Property 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_SelectProperty {
            get {
                return ResourceManager.GetString("Res_Notice_SelectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update By 的本地化字符串。
        /// </summary>
        internal static string Res_Notice_UpdateBy {
            get {
                return ResourceManager.GetString("Res_Notice_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        internal static string Res_OnlinepayReady_Confirm {
            get {
                return ResourceManager.GetString("Res_OnlinepayReady_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Amount: 的本地化字符串。
        /// </summary>
        internal static string Res_OnlinepayReady_PaymentAmount {
            get {
                return ResourceManager.GetString("Res_OnlinepayReady_PaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pay with PPS 的本地化字符串。
        /// </summary>
        internal static string Res_OnlinepayReady_PayWithPPS {
            get {
                return ResourceManager.GetString("Res_OnlinepayReady_PayWithPPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Premise Name: 的本地化字符串。
        /// </summary>
        internal static string Res_OnlinepayReady_PremiseName {
            get {
                return ResourceManager.GetString("Res_OnlinepayReady_PremiseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_Amount {
            get {
                return ResourceManager.GetString("Res_Onlinepay_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Charge Item 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_ChargeItem {
            get {
                return ResourceManager.GetString("Res_Onlinepay_ChargeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name : 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_CustName {
            get {
                return ResourceManager.GetString("Res_Onlinepay_CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_Desc {
            get {
                return ResourceManager.GetString("Res_Onlinepay_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Due Date 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_Duedate {
            get {
                return ResourceManager.GetString("Res_Onlinepay_Duedate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_Gridview_ChooseAll {
            get {
                return ResourceManager.GetString("Res_Onlinepay_Gridview_ChooseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment History 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_History {
            get {
                return ResourceManager.GetString("Res_Onlinepay_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Number : 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_LeaseNum {
            get {
                return ResourceManager.GetString("Res_Onlinepay_LeaseNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merchant Information 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_MerInfo {
            get {
                return ResourceManager.GetString("Res_Onlinepay_MerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outstanding 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_Outstandingamount {
            get {
                return ResourceManager.GetString("Res_Onlinepay_Outstandingamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pay 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_Pay {
            get {
                return ResourceManager.GetString("Res_Onlinepay_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Amount :  的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_PaymentAmount {
            get {
                return ResourceManager.GetString("Res_Onlinepay_PaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Date 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_PaymentDate {
            get {
                return ResourceManager.GetString("Res_Onlinepay_PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction No 的本地化字符串。
        /// </summary>
        internal static string Res_Onlinepay_TransactionNo {
            get {
                return ResourceManager.GetString("Res_Onlinepay_TransactionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        internal static string Res_Operation {
            get {
                return ResourceManager.GetString("Res_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Balance 的本地化字符串。
        /// </summary>
        internal static string Res_Op_CurrentBalance {
            get {
                return ResourceManager.GetString("Res_Op_CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currency 的本地化字符串。
        /// </summary>
        internal static string Res_Payhistory_Currency {
            get {
                return ResourceManager.GetString("Res_Payhistory_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pay Amount 的本地化字符串。
        /// </summary>
        internal static string Res_Payhistory_Payamount {
            get {
                return ResourceManager.GetString("Res_Payhistory_Payamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pay Date 的本地化字符串。
        /// </summary>
        internal static string Res_Payhistory_Paydate {
            get {
                return ResourceManager.GetString("Res_Payhistory_Paydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment History 的本地化字符串。
        /// </summary>
        internal static string Res_Payhistory_PaymentHistory {
            get {
                return ResourceManager.GetString("Res_Payhistory_PaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pay Result 的本地化字符串。
        /// </summary>
        internal static string Res_Payhistory_Payresult {
            get {
                return ResourceManager.GetString("Res_Payhistory_Payresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        internal static string Res_Phone {
            get {
                return ResourceManager.GetString("Res_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position 的本地化字符串。
        /// </summary>
        internal static string Res_Position {
            get {
                return ResourceManager.GetString("Res_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        internal static string Res_Preview {
            get {
                return ResourceManager.GetString("Res_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary 的本地化字符串。
        /// </summary>
        internal static string Res_Primary {
            get {
                return ResourceManager.GetString("Res_Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Privacy Policy 的本地化字符串。
        /// </summary>
        internal static string Res_Privacy_Policy {
            get {
                return ResourceManager.GetString("Res_Privacy_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic Infomation 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_BasicInfo {
            get {
                return ResourceManager.GetString("Res_Profile_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Billing Address 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_BillAddr {
            get {
                return ResourceManager.GetString("Res_Profile_BillAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_ChangeEmail {
            get {
                return ResourceManager.GetString("Res_Profile_ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_Contact {
            get {
                return ResourceManager.GetString("Res_Profile_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Number 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_ContactNum {
            get {
                return ResourceManager.GetString("Res_Profile_ContactNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contact Person 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_ContactPerson {
            get {
                return ResourceManager.GetString("Res_Profile_ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Name 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_CustName {
            get {
                return ResourceManager.GetString("Res_Profile_CustName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Number 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_CustNum {
            get {
                return ResourceManager.GetString("Res_Profile_CustNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Address 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_Email {
            get {
                return ResourceManager.GetString("Res_Profile_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Information 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_LeaseInfo {
            get {
                return ResourceManager.GetString("Res_Profile_LeaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Number 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_LeaseNum {
            get {
                return ResourceManager.GetString("Res_Profile_LeaseNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Period 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_LeasePeriod {
            get {
                return ResourceManager.GetString("Res_Profile_LeasePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_Others {
            get {
                return ResourceManager.GetString("Res_Profile_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Premises 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_Premises {
            get {
                return ResourceManager.GetString("Res_Profile_Premises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade Name 的本地化字符串。
        /// </summary>
        internal static string Res_Profile_TradeName {
            get {
                return ResourceManager.GetString("Res_Profile_TradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property 的本地化字符串。
        /// </summary>
        internal static string Res_Property {
            get {
                return ResourceManager.GetString("Res_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Billing Email 的本地化字符串。
        /// </summary>
        internal static string Res_Property_Billing_Email {
            get {
                return ResourceManager.GetString("Res_Property_Billing_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Billing Phone 的本地化字符串。
        /// </summary>
        internal static string Res_Property_Billing_Phone {
            get {
                return ResourceManager.GetString("Res_Property_Billing_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Code 的本地化字符串。
        /// </summary>
        internal static string Res_Property_Code {
            get {
                return ResourceManager.GetString("Res_Property_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Editor 的本地化字符串。
        /// </summary>
        internal static string Res_Property_Editor {
            get {
                return ResourceManager.GetString("Res_Property_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EM Email 的本地化字符串。
        /// </summary>
        internal static string Res_Property_EM_Email {
            get {
                return ResourceManager.GetString("Res_Property_EM_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leasing Email 的本地化字符串。
        /// </summary>
        internal static string Res_Property_Leasing_Email {
            get {
                return ResourceManager.GetString("Res_Property_Leasing_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leasing Phone 的本地化字符串。
        /// </summary>
        internal static string Res_Property_Leasing_Phone {
            get {
                return ResourceManager.GetString("Res_Property_Leasing_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_Property_Maintenance {
            get {
                return ResourceManager.GetString("Res_Property_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property Name 的本地化字符串。
        /// </summary>
        internal static string Res_Property_Name {
            get {
                return ResourceManager.GetString("Res_Property_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel Process 的本地化字符串。
        /// </summary>
        internal static string Res_Register_ButtonCancel {
            get {
                return ResourceManager.GetString("Res_Register_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue Process 的本地化字符串。
        /// </summary>
        internal static string Res_Register_ButtonContinue {
            get {
                return ResourceManager.GetString("Res_Register_ButtonContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Res_Register_Cancel {
            get {
                return ResourceManager.GetString("Res_Register_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to cancel this process? 的本地化字符串。
        /// </summary>
        internal static string Res_Register_CancelProcess {
            get {
                return ResourceManager.GetString("Res_Register_CancelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I have read and agree to be bound by the said Important Note (if applicable) and the said Terms and Conditions. 的本地化字符串。
        /// </summary>
        internal static string Res_Register_CheckBox {
            get {
                return ResourceManager.GetString("Res_Register_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 click here 的本地化字符串。
        /// </summary>
        internal static string Res_Register_CheckBox_ClickHere {
            get {
                return ResourceManager.GetString("Res_Register_CheckBox_ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please 的本地化字符串。
        /// </summary>
        internal static string Res_Register_CheckBox_Please {
            get {
                return ResourceManager.GetString("Res_Register_CheckBox_Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 to read the Important Note on eStatement Service Arrangement (if applicable) and the Terms and Conditions. 的本地化字符串。
        /// </summary>
        internal static string Res_Register_CheckBox_ReadTerms {
            get {
                return ResourceManager.GetString("Res_Register_CheckBox_ReadTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement balance 的本地化字符串。
        /// </summary>
        internal static string Res_Register_CurrentBalance {
            get {
                return ResourceManager.GetString("Res_Register_CurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Res_Register_Email {
            get {
                return ResourceManager.GetString("Res_Register_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease expiry date 的本地化字符串。
        /// </summary>
        internal static string Res_Register_ExpiryDate {
            get {
                return ResourceManager.GetString("Res_Register_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lease Number 的本地化字符串。
        /// </summary>
        internal static string Res_Register_LeaseNumber {
            get {
                return ResourceManager.GetString("Res_Register_LeaseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monthly rental amount 的本地化字符串。
        /// </summary>
        internal static string Res_Register_MonthlyRental {
            get {
                return ResourceManager.GetString("Res_Register_MonthlyRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        internal static string Res_Register_Register {
            get {
                return ResourceManager.GetString("Res_Register_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security question 1 的本地化字符串。
        /// </summary>
        internal static string Res_Register_SecurityQuestion1 {
            get {
                return ResourceManager.GetString("Res_Register_SecurityQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security question 2 的本地化字符串。
        /// </summary>
        internal static string Res_Register_SecurityQuestion2 {
            get {
                return ResourceManager.GetString("Res_Register_SecurityQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement number (within 3 month) 的本地化字符串。
        /// </summary>
        internal static string Res_Register_StatementNumber {
            get {
                return ResourceManager.GetString("Res_Register_StatementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register Success 的本地化字符串。
        /// </summary>
        internal static string Res_Register_Success {
            get {
                return ResourceManager.GetString("Res_Register_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The information collected in this website will be used by Hutchison Estate Agents Limited (“HEAL”) for the provision of e-statement service and other purposes in connection therewith.  You have the right to request access to and correction of your personal data, details of the person who will handle such request and the privacy policy of HEAL are contained in the “Privacy Policy” section of this website. 的本地化字符串。
        /// </summary>
        internal static string Res_Rider {
            get {
                return ResourceManager.GetString("Res_Rider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        internal static string Res_Role {
            get {
                return ResourceManager.GetString("Res_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Res_Save {
            get {
                return ResourceManager.GetString("Res_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Edit Customer User 的本地化字符串。
        /// </summary>
        internal static string Res_Save_Edit_Customer_User {
            get {
                return ResourceManager.GetString("Res_Save_Edit_Customer_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Edit Group 的本地化字符串。
        /// </summary>
        internal static string Res_Save_Edit_Group {
            get {
                return ResourceManager.GetString("Res_Save_Edit_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Edit User 的本地化字符串。
        /// </summary>
        internal static string Res_Save_Edit_User {
            get {
                return ResourceManager.GetString("Res_Save_Edit_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save New Customer User 的本地化字符串。
        /// </summary>
        internal static string Res_Save_New_Customer_User {
            get {
                return ResourceManager.GetString("Res_Save_New_Customer_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save New Group 的本地化字符串。
        /// </summary>
        internal static string Res_Save_New_Group {
            get {
                return ResourceManager.GetString("Res_Save_New_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save New User 的本地化字符串。
        /// </summary>
        internal static string Res_Save_New_User {
            get {
                return ResourceManager.GetString("Res_Save_New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select A Group 的本地化字符串。
        /// </summary>
        internal static string Res_Select_A_Group {
            get {
                return ResourceManager.GetString("Res_Select_A_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Group 的本地化字符串。
        /// </summary>
        internal static string Res_Select_Group {
            get {
                return ResourceManager.GetString("Res_Select_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send email 的本地化字符串。
        /// </summary>
        internal static string Res_Send_Mail {
            get {
                return ResourceManager.GetString("Res_Send_Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Mail(Batch) 的本地化字符串。
        /// </summary>
        internal static string Res_Send_Mail_Batch {
            get {
                return ResourceManager.GetString("Res_Send_Mail_Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string Res_Site_Alert_OK {
            get {
                return ResourceManager.GetString("Res_Site_Alert_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notice 的本地化字符串。
        /// </summary>
        internal static string Res_Site_Alert_Title {
            get {
                return ResourceManager.GetString("Res_Site_Alert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string Res_Site_Search {
            get {
                return ResourceManager.GetString("Res_Site_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Date 的本地化字符串。
        /// </summary>
        internal static string Res_Start_Date {
            get {
                return ResourceManager.GetString("Res_Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download PDF 的本地化字符串。
        /// </summary>
        internal static string Res_StatementViewer_Download {
            get {
                return ResourceManager.GetString("Res_StatementViewer_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        internal static string Res_Statement_ButtonDetail {
            get {
                return ResourceManager.GetString("Res_Statement_ButtonDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detail 的本地化字符串。
        /// </summary>
        internal static string Res_Statement_Detail {
            get {
                return ResourceManager.GetString("Res_Statement_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Due Date 的本地化字符串。
        /// </summary>
        internal static string Res_Statement_PaymentDueDate {
            get {
                return ResourceManager.GetString("Res_Statement_PaymentDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement Amount 的本地化字符串。
        /// </summary>
        internal static string Res_Statement_StatementAmount {
            get {
                return ResourceManager.GetString("Res_Statement_StatementAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement Date 的本地化字符串。
        /// </summary>
        internal static string Res_Statement_StatementDate {
            get {
                return ResourceManager.GetString("Res_Statement_StatementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statement Number 的本地化字符串。
        /// </summary>
        internal static string Res_Statement_StatementNumber {
            get {
                return ResourceManager.GetString("Res_Statement_StatementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Res_Status {
            get {
                return ResourceManager.GetString("Res_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        internal static string Res_Status1 {
            get {
                return ResourceManager.GetString("Res_Status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subject 的本地化字符串。
        /// </summary>
        internal static string Res_Subject {
            get {
                return ResourceManager.GetString("Res_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User List 的本地化字符串。
        /// </summary>
        internal static string Res_Users {
            get {
                return ResourceManager.GetString("Res_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Group 的本地化字符串。
        /// </summary>
        internal static string Res_User_Group {
            get {
                return ResourceManager.GetString("Res_User_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Group Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_User_Group_Maintenance {
            get {
                return ResourceManager.GetString("Res_User_Group_Maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Id 的本地化字符串。
        /// </summary>
        internal static string Res_User_Id {
            get {
                return ResourceManager.GetString("Res_User_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Maintenance 的本地化字符串。
        /// </summary>
        internal static string Res_User_Maintenance {
            get {
                return ResourceManager.GetString("Res_User_Maintenance", resourceCulture);
            }
        }
    }
}
